Opinion: Un camino para ser Frontend Developer
sergiodxa/impresionante-javascript pull request #79
Opened 2018-05-02 18:04 UTC by juandc

Link al tutorial: [Un camino para ser Frontend Developer](https://platzi.com/html5-css3/tutoriales/un-camino-para-ser-frontend-developer/) :neckbeard:

2018-05-02 20:41 UTC, juandc commented
Conflicts solved :+1:

2018-05-02 23:54 UTC, sergiodxa requested changes

2018-05-02 23:54 UTC, sergiodxa commented on README.md
> +- [Sobre el ecosistema y la fatiga de JavaScript](https://medium.com/@sergiodxa/73027048413f) - Reflexiones sobre el estado actual de la comunidad JavaScript y la conocida fatiga de JS.
Falta una línea en blanco acá

2018-05-03 00:16 UTC, juandc commented
Listo :tada:

2018-05-03 04:49 UTC, sergiodxa approved these changes

2018-05-03 04:49 UTC, merged